name: Unity WebGL Build

on:
  push:
    branches: [ main ]
  # pull_request:

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository containing your Unity project.
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Build the Unity project for WebGL using game-ci/unity-builder.
      - name: Build Unity Project (WebGL)
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL
          # Specify your Unity version if necessary (e.g., "2021.3.12f1"). Otherwise, it will try to auto-detect from the project.
          unityVersion: "6000.0.36f1"
          # Optionally specify the build method if you have a custom build script:
          # executeMethod: BuildScript.PerformWebGLBuild
          # Optionally specify an output directory (default is "Build")
          buildPath: Build/WebGL

      # Step 3: Upload the built WebGL project as a build artifact.
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild
          path: Build/WebGL
